spring.application.name=idmrs-backend
spring.application.name=idmrs-backend
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.dialect=${SPRING_JPA_HIBERNATE_DIALECT}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.springframework=INFO
logging.level.com.idmrs.backend=DEBUG
server.port=${PORT:8081}


